// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_common_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_common_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_common_2eproto;
namespace jukey {
namespace prot {
class NetStream;
struct NetStreamDefaultTypeInternal;
extern NetStreamDefaultTypeInternal _NetStream_default_instance_;
}  // namespace prot
}  // namespace jukey
PROTOBUF_NAMESPACE_OPEN
template<> ::jukey::prot::NetStream* Arena::CreateMaybeMessage<::jukey::prot::NetStream>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace jukey {
namespace prot {

// ===================================================================

class NetStream final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jukey.prot.NetStream) */ {
 public:
  inline NetStream() : NetStream(nullptr) {}
  ~NetStream() override;
  explicit PROTOBUF_CONSTEXPR NetStream(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NetStream(const NetStream& from);
  NetStream(NetStream&& from) noexcept
    : NetStream() {
    *this = ::std::move(from);
  }

  inline NetStream& operator=(const NetStream& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetStream& operator=(NetStream&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NetStream& default_instance() {
    return *internal_default_instance();
  }
  static inline const NetStream* internal_default_instance() {
    return reinterpret_cast<const NetStream*>(
               &_NetStream_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NetStream& a, NetStream& b) {
    a.Swap(&b);
  }
  inline void Swap(NetStream* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetStream* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NetStream* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NetStream>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NetStream& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NetStream& from) {
    NetStream::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NetStream* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jukey.prot.NetStream";
  }
  protected:
  explicit NetStream(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStreamIdFieldNumber = 4,
    kMediaSrcIdFieldNumber = 6,
    kAppIdFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kStreamTypeFieldNumber = 3,
    kMediaSrcTypeFieldNumber = 5,
  };
  // required string stream_id = 4;
  bool has_stream_id() const;
  private:
  bool _internal_has_stream_id() const;
  public:
  void clear_stream_id();
  const std::string& stream_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stream_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stream_id();
  PROTOBUF_NODISCARD std::string* release_stream_id();
  void set_allocated_stream_id(std::string* stream_id);
  private:
  const std::string& _internal_stream_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stream_id(const std::string& value);
  std::string* _internal_mutable_stream_id();
  public:

  // required string media_src_id = 6;
  bool has_media_src_id() const;
  private:
  bool _internal_has_media_src_id() const;
  public:
  void clear_media_src_id();
  const std::string& media_src_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_media_src_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_media_src_id();
  PROTOBUF_NODISCARD std::string* release_media_src_id();
  void set_allocated_media_src_id(std::string* media_src_id);
  private:
  const std::string& _internal_media_src_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_media_src_id(const std::string& value);
  std::string* _internal_mutable_media_src_id();
  public:

  // required uint32 app_id = 1;
  bool has_app_id() const;
  private:
  bool _internal_has_app_id() const;
  public:
  void clear_app_id();
  uint32_t app_id() const;
  void set_app_id(uint32_t value);
  private:
  uint32_t _internal_app_id() const;
  void _internal_set_app_id(uint32_t value);
  public:

  // required uint32 user_id = 2;
  bool has_user_id() const;
  private:
  bool _internal_has_user_id() const;
  public:
  void clear_user_id();
  uint32_t user_id() const;
  void set_user_id(uint32_t value);
  private:
  uint32_t _internal_user_id() const;
  void _internal_set_user_id(uint32_t value);
  public:

  // required uint32 stream_type = 3;
  bool has_stream_type() const;
  private:
  bool _internal_has_stream_type() const;
  public:
  void clear_stream_type();
  uint32_t stream_type() const;
  void set_stream_type(uint32_t value);
  private:
  uint32_t _internal_stream_type() const;
  void _internal_set_stream_type(uint32_t value);
  public:

  // required uint32 media_src_type = 5;
  bool has_media_src_type() const;
  private:
  bool _internal_has_media_src_type() const;
  public:
  void clear_media_src_type();
  uint32_t media_src_type() const;
  void set_media_src_type(uint32_t value);
  private:
  uint32_t _internal_media_src_type() const;
  void _internal_set_media_src_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:jukey.prot.NetStream)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stream_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr media_src_id_;
    uint32_t app_id_;
    uint32_t user_id_;
    uint32_t stream_type_;
    uint32_t media_src_type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NetStream

// required uint32 app_id = 1;
inline bool NetStream::_internal_has_app_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool NetStream::has_app_id() const {
  return _internal_has_app_id();
}
inline void NetStream::clear_app_id() {
  _impl_.app_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t NetStream::_internal_app_id() const {
  return _impl_.app_id_;
}
inline uint32_t NetStream::app_id() const {
  // @@protoc_insertion_point(field_get:jukey.prot.NetStream.app_id)
  return _internal_app_id();
}
inline void NetStream::_internal_set_app_id(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.app_id_ = value;
}
inline void NetStream::set_app_id(uint32_t value) {
  _internal_set_app_id(value);
  // @@protoc_insertion_point(field_set:jukey.prot.NetStream.app_id)
}

// required uint32 user_id = 2;
inline bool NetStream::_internal_has_user_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool NetStream::has_user_id() const {
  return _internal_has_user_id();
}
inline void NetStream::clear_user_id() {
  _impl_.user_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline uint32_t NetStream::_internal_user_id() const {
  return _impl_.user_id_;
}
inline uint32_t NetStream::user_id() const {
  // @@protoc_insertion_point(field_get:jukey.prot.NetStream.user_id)
  return _internal_user_id();
}
inline void NetStream::_internal_set_user_id(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.user_id_ = value;
}
inline void NetStream::set_user_id(uint32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:jukey.prot.NetStream.user_id)
}

// required uint32 stream_type = 3;
inline bool NetStream::_internal_has_stream_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool NetStream::has_stream_type() const {
  return _internal_has_stream_type();
}
inline void NetStream::clear_stream_type() {
  _impl_.stream_type_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline uint32_t NetStream::_internal_stream_type() const {
  return _impl_.stream_type_;
}
inline uint32_t NetStream::stream_type() const {
  // @@protoc_insertion_point(field_get:jukey.prot.NetStream.stream_type)
  return _internal_stream_type();
}
inline void NetStream::_internal_set_stream_type(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.stream_type_ = value;
}
inline void NetStream::set_stream_type(uint32_t value) {
  _internal_set_stream_type(value);
  // @@protoc_insertion_point(field_set:jukey.prot.NetStream.stream_type)
}

// required string stream_id = 4;
inline bool NetStream::_internal_has_stream_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool NetStream::has_stream_id() const {
  return _internal_has_stream_id();
}
inline void NetStream::clear_stream_id() {
  _impl_.stream_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& NetStream::stream_id() const {
  // @@protoc_insertion_point(field_get:jukey.prot.NetStream.stream_id)
  return _internal_stream_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void NetStream::set_stream_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.stream_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jukey.prot.NetStream.stream_id)
}
inline std::string* NetStream::mutable_stream_id() {
  std::string* _s = _internal_mutable_stream_id();
  // @@protoc_insertion_point(field_mutable:jukey.prot.NetStream.stream_id)
  return _s;
}
inline const std::string& NetStream::_internal_stream_id() const {
  return _impl_.stream_id_.Get();
}
inline void NetStream::_internal_set_stream_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.stream_id_.Set(value, GetArenaForAllocation());
}
inline std::string* NetStream::_internal_mutable_stream_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.stream_id_.Mutable(GetArenaForAllocation());
}
inline std::string* NetStream::release_stream_id() {
  // @@protoc_insertion_point(field_release:jukey.prot.NetStream.stream_id)
  if (!_internal_has_stream_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.stream_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stream_id_.IsDefault()) {
    _impl_.stream_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void NetStream::set_allocated_stream_id(std::string* stream_id) {
  if (stream_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.stream_id_.SetAllocated(stream_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stream_id_.IsDefault()) {
    _impl_.stream_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jukey.prot.NetStream.stream_id)
}

// required uint32 media_src_type = 5;
inline bool NetStream::_internal_has_media_src_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool NetStream::has_media_src_type() const {
  return _internal_has_media_src_type();
}
inline void NetStream::clear_media_src_type() {
  _impl_.media_src_type_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline uint32_t NetStream::_internal_media_src_type() const {
  return _impl_.media_src_type_;
}
inline uint32_t NetStream::media_src_type() const {
  // @@protoc_insertion_point(field_get:jukey.prot.NetStream.media_src_type)
  return _internal_media_src_type();
}
inline void NetStream::_internal_set_media_src_type(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.media_src_type_ = value;
}
inline void NetStream::set_media_src_type(uint32_t value) {
  _internal_set_media_src_type(value);
  // @@protoc_insertion_point(field_set:jukey.prot.NetStream.media_src_type)
}

// required string media_src_id = 6;
inline bool NetStream::_internal_has_media_src_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool NetStream::has_media_src_id() const {
  return _internal_has_media_src_id();
}
inline void NetStream::clear_media_src_id() {
  _impl_.media_src_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& NetStream::media_src_id() const {
  // @@protoc_insertion_point(field_get:jukey.prot.NetStream.media_src_id)
  return _internal_media_src_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void NetStream::set_media_src_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.media_src_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:jukey.prot.NetStream.media_src_id)
}
inline std::string* NetStream::mutable_media_src_id() {
  std::string* _s = _internal_mutable_media_src_id();
  // @@protoc_insertion_point(field_mutable:jukey.prot.NetStream.media_src_id)
  return _s;
}
inline const std::string& NetStream::_internal_media_src_id() const {
  return _impl_.media_src_id_.Get();
}
inline void NetStream::_internal_set_media_src_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.media_src_id_.Set(value, GetArenaForAllocation());
}
inline std::string* NetStream::_internal_mutable_media_src_id() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.media_src_id_.Mutable(GetArenaForAllocation());
}
inline std::string* NetStream::release_media_src_id() {
  // @@protoc_insertion_point(field_release:jukey.prot.NetStream.media_src_id)
  if (!_internal_has_media_src_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.media_src_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.media_src_id_.IsDefault()) {
    _impl_.media_src_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void NetStream::set_allocated_media_src_id(std::string* media_src_id) {
  if (media_src_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.media_src_id_.SetAllocated(media_src_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.media_src_id_.IsDefault()) {
    _impl_.media_src_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:jukey.prot.NetStream.media_src_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace prot
}  // namespace jukey

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_common_2eproto
