// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mq.proto

#include "mq.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace jukey {
namespace prot {
PROTOBUF_CONSTEXPR MqMsg::MqMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.instance_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.exchange_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.routing_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.user_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.trace_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.extend_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.service_type_)*/0u} {}
struct MqMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MqMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MqMsgDefaultTypeInternal() {}
  union {
    MqMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MqMsgDefaultTypeInternal _MqMsg_default_instance_;
}  // namespace prot
}  // namespace jukey
static ::_pb::Metadata file_level_metadata_mq_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_mq_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_mq_2eproto = nullptr;

const uint32_t TableStruct_mq_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::jukey::prot::MqMsg, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::jukey::prot::MqMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::jukey::prot::MqMsg, _impl_.service_type_),
  PROTOBUF_FIELD_OFFSET(::jukey::prot::MqMsg, _impl_.instance_id_),
  PROTOBUF_FIELD_OFFSET(::jukey::prot::MqMsg, _impl_.exchange_),
  PROTOBUF_FIELD_OFFSET(::jukey::prot::MqMsg, _impl_.routing_key_),
  PROTOBUF_FIELD_OFFSET(::jukey::prot::MqMsg, _impl_.user_data_),
  PROTOBUF_FIELD_OFFSET(::jukey::prot::MqMsg, _impl_.trace_data_),
  PROTOBUF_FIELD_OFFSET(::jukey::prot::MqMsg, _impl_.extend_data_),
  6,
  0,
  1,
  2,
  3,
  4,
  5,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 13, -1, sizeof(::jukey::prot::MqMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::jukey::prot::_MqMsg_default_instance_._instance,
};

const char descriptor_table_protodef_mq_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\010mq.proto\022\njukey.prot\"\225\001\n\005MqMsg\022\024\n\014serv"
  "ice_type\030\001 \002(\r\022\023\n\013instance_id\030\002 \002(\t\022\020\n\010e"
  "xchange\030\003 \001(\t\022\023\n\013routing_key\030\004 \001(\t\022\021\n\tus"
  "er_data\030\005 \001(\t\022\022\n\ntrace_data\030\006 \001(\t\022\023\n\013ext"
  "end_data\030\007 \001(\t"
  ;
static ::_pbi::once_flag descriptor_table_mq_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_mq_2eproto = {
    false, false, 174, descriptor_table_protodef_mq_2eproto,
    "mq.proto",
    &descriptor_table_mq_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_mq_2eproto::offsets,
    file_level_metadata_mq_2eproto, file_level_enum_descriptors_mq_2eproto,
    file_level_service_descriptors_mq_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_mq_2eproto_getter() {
  return &descriptor_table_mq_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_mq_2eproto(&descriptor_table_mq_2eproto);
namespace jukey {
namespace prot {

// ===================================================================

class MqMsg::_Internal {
 public:
  using HasBits = decltype(std::declval<MqMsg>()._impl_._has_bits_);
  static void set_has_service_type(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_instance_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_exchange(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_routing_key(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_user_data(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_trace_data(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_extend_data(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000041) ^ 0x00000041) != 0;
  }
};

MqMsg::MqMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:jukey.prot.MqMsg)
}
MqMsg::MqMsg(const MqMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MqMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.instance_id_){}
    , decltype(_impl_.exchange_){}
    , decltype(_impl_.routing_key_){}
    , decltype(_impl_.user_data_){}
    , decltype(_impl_.trace_data_){}
    , decltype(_impl_.extend_data_){}
    , decltype(_impl_.service_type_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.instance_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instance_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_instance_id()) {
    _this->_impl_.instance_id_.Set(from._internal_instance_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.exchange_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_exchange()) {
    _this->_impl_.exchange_.Set(from._internal_exchange(), 
      _this->GetArenaForAllocation());
  }
  _impl_.routing_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.routing_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_routing_key()) {
    _this->_impl_.routing_key_.Set(from._internal_routing_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.user_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_user_data()) {
    _this->_impl_.user_data_.Set(from._internal_user_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.trace_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.trace_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_trace_data()) {
    _this->_impl_.trace_data_.Set(from._internal_trace_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.extend_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.extend_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_extend_data()) {
    _this->_impl_.extend_data_.Set(from._internal_extend_data(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.service_type_ = from._impl_.service_type_;
  // @@protoc_insertion_point(copy_constructor:jukey.prot.MqMsg)
}

inline void MqMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.instance_id_){}
    , decltype(_impl_.exchange_){}
    , decltype(_impl_.routing_key_){}
    , decltype(_impl_.user_data_){}
    , decltype(_impl_.trace_data_){}
    , decltype(_impl_.extend_data_){}
    , decltype(_impl_.service_type_){0u}
  };
  _impl_.instance_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instance_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchange_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.routing_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.routing_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.user_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.trace_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.trace_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.extend_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.extend_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MqMsg::~MqMsg() {
  // @@protoc_insertion_point(destructor:jukey.prot.MqMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MqMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.instance_id_.Destroy();
  _impl_.exchange_.Destroy();
  _impl_.routing_key_.Destroy();
  _impl_.user_data_.Destroy();
  _impl_.trace_data_.Destroy();
  _impl_.extend_data_.Destroy();
}

void MqMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MqMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:jukey.prot.MqMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.instance_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.exchange_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.routing_key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.user_data_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.trace_data_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      _impl_.extend_data_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.service_type_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MqMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required uint32 service_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_service_type(&has_bits);
          _impl_.service_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required string instance_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_instance_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "jukey.prot.MqMsg.instance_id");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string exchange = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_exchange();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "jukey.prot.MqMsg.exchange");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string routing_key = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_routing_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "jukey.prot.MqMsg.routing_key");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string user_data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_user_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "jukey.prot.MqMsg.user_data");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string trace_data = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_trace_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "jukey.prot.MqMsg.trace_data");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string extend_data = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_extend_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "jukey.prot.MqMsg.extend_data");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MqMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jukey.prot.MqMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required uint32 service_type = 1;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_service_type(), target);
  }

  // required string instance_id = 2;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_instance_id().data(), static_cast<int>(this->_internal_instance_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "jukey.prot.MqMsg.instance_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_instance_id(), target);
  }

  // optional string exchange = 3;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_exchange().data(), static_cast<int>(this->_internal_exchange().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "jukey.prot.MqMsg.exchange");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_exchange(), target);
  }

  // optional string routing_key = 4;
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_routing_key().data(), static_cast<int>(this->_internal_routing_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "jukey.prot.MqMsg.routing_key");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_routing_key(), target);
  }

  // optional string user_data = 5;
  if (cached_has_bits & 0x00000008u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_user_data().data(), static_cast<int>(this->_internal_user_data().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "jukey.prot.MqMsg.user_data");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_user_data(), target);
  }

  // optional string trace_data = 6;
  if (cached_has_bits & 0x00000010u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_trace_data().data(), static_cast<int>(this->_internal_trace_data().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "jukey.prot.MqMsg.trace_data");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_trace_data(), target);
  }

  // optional string extend_data = 7;
  if (cached_has_bits & 0x00000020u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_extend_data().data(), static_cast<int>(this->_internal_extend_data().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "jukey.prot.MqMsg.extend_data");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_extend_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jukey.prot.MqMsg)
  return target;
}

size_t MqMsg::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:jukey.prot.MqMsg)
  size_t total_size = 0;

  if (_internal_has_instance_id()) {
    // required string instance_id = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_instance_id());
  }

  if (_internal_has_service_type()) {
    // required uint32 service_type = 1;
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_service_type());
  }

  return total_size;
}
size_t MqMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jukey.prot.MqMsg)
  size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x00000041) ^ 0x00000041) == 0) {  // All required fields are present.
    // required string instance_id = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_instance_id());

    // required uint32 service_type = 1;
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_service_type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003eu) {
    // optional string exchange = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_exchange());
    }

    // optional string routing_key = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_routing_key());
    }

    // optional string user_data = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_user_data());
    }

    // optional string trace_data = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_trace_data());
    }

    // optional string extend_data = 7;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_extend_data());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MqMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MqMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MqMsg::GetClassData() const { return &_class_data_; }


void MqMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MqMsg*>(&to_msg);
  auto& from = static_cast<const MqMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:jukey.prot.MqMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_instance_id(from._internal_instance_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_exchange(from._internal_exchange());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_routing_key(from._internal_routing_key());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_user_data(from._internal_user_data());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_trace_data(from._internal_trace_data());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_set_extend_data(from._internal_extend_data());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.service_type_ = from._impl_.service_type_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MqMsg::CopyFrom(const MqMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jukey.prot.MqMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MqMsg::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void MqMsg::InternalSwap(MqMsg* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.instance_id_, lhs_arena,
      &other->_impl_.instance_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.exchange_, lhs_arena,
      &other->_impl_.exchange_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.routing_key_, lhs_arena,
      &other->_impl_.routing_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.user_data_, lhs_arena,
      &other->_impl_.user_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.trace_data_, lhs_arena,
      &other->_impl_.trace_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.extend_data_, lhs_arena,
      &other->_impl_.extend_data_, rhs_arena
  );
  swap(_impl_.service_type_, other->_impl_.service_type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MqMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mq_2eproto_getter, &descriptor_table_mq_2eproto_once,
      file_level_metadata_mq_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace prot
}  // namespace jukey
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::jukey::prot::MqMsg*
Arena::CreateMaybeMessage< ::jukey::prot::MqMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::jukey::prot::MqMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
